services:

  # ===========================
  # AUTH DATABASE
  # ===========================
  auth_db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - aivent-net

  # ===========================
  # RABBITMQ
  # ===========================
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - aivent-net

  # ===========================
  # REDIS
  # ===========================
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - aivent-net

  # ===========================
  # AUTH SERVICE
  # ===========================
  auth_service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    depends_on:
      - auth_db
      - rabbitmq
      - redis
    env_file:
      - ./auth-service/.env
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service/private.pem:/app/private.pem
    networks:
      - aivent-net
    command: >
      sh -c "
        /wait-for-db.sh auth_db 5432 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  auth_celery_worker:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    command: celery -A auth_project worker --loglevel=info --concurrency=2
    depends_on:
      - rabbitmq
      - redis
      - auth_service
    env_file:
      - ./auth-service/.env
    networks:
      - aivent-net

  auth_celery_beat:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    command: celery -A auth_project beat --loglevel=info
    depends_on:
      - rabbitmq
      - redis
      - auth_service
    env_file:
      - ./auth-service/.env
    networks:
      - aivent-net

  # ===========================
  # USER SERVICE + DB
  # ===========================
  user_db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - aivent-net

  user_service:
    build:
      context: ./user-service
    depends_on:
      - user_db
    env_file:
      - ./user-service/.env
    environment:
      AUTH_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA65BLY/RNrumS93/3Vtu8
        hF1RlguSbw2iAcKyynZty3G+VFfYIrwhKVLVHBIrW+ix1gtZ6v7UowrxYj5sBTh9
        ZS/J+GL5N9oxr6h6rpFn66BaFoYA/U10C7Xu4J0exlGdWMv7GWQNAli6sOT9Vvcb
        16OonF5xp/2Qvk7uDQI5BVWWw7GuL1s/lZZGceJ1LL8LYt4AolY1LLWdR3LujamA
        qdHs6HX7dgOZAEi3FvHRdn+0eRD5fqZSYqWTIKmACfOppf9d28TQ8pkc9fiFzKMo
        Qly7rx1+b2sVAxkGxwgcjDPmm9sJSAAYlN+HJsngHzc1lZWdrpVlYF4F/Dzm+dzv
        0wIDAQAB
        -----END PUBLIC KEY-----
    ports:
      - "8001:8000"
    networks:
      - aivent-net
    command: >
      sh -c "
        /wait-for-db.sh user_db 5432 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "


  # ===========================
  # VENDOR SERVICE + DB
  # ===========================
  vendor_db:
    image: postgres:15
    environment:
      POSTGRES_DB: vendor_db
      POSTGRES_USER: vendor
      POSTGRES_PASSWORD: vendorpass
    ports:
      - "5436:5432"
    volumes:
      - vendor_db_data:/var/lib/postgresql/data
    networks:
      - aivent-net

  vendor_service:
    build:
      context: ./vendor-service
    depends_on:
      - vendor_db
    env_file:
      - ./vendor-service/.env
    ports:
      - "8002:8000"
    networks:
      - aivent-net
    command: >
      sh -c "
        /wait-for-db.sh vendor_db 5432 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

networks:
  aivent-net:

volumes:
  auth_db_data:
  user_db_data:
  vendor_db_data:
